### ISSUE TITLE
Py-cordex installs the `tests` package

### ISSUE THREAD

**Issue by zklaus** [conda-forge/py-cordex-feedstock#23]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The conda-forge package installs the `tests` package as a top-level package. This usually indicates a problem in the `pyproject.toml` (or `setup.{cfg,py}`) file, where the `tests` are installed as if they were a normal package. This should probably be addressed upstream, though a removal in the install script here is possible.

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by larsbuntemeyer** [comment]
Thanks for catching this! It's true, the `packages` option in `setup.cfg` was never truly defined.
